export const colors = {
  background: '#fbf9f4',
  surface: '#fbf9f4',
  surfaceLowest: '#ffffff',
  surfaceLow: '#f5f3ee',
  surfaceContainer: '#f0eee9',
  surfaceHigh: '#eae8e3',
  surfaceHighest: '#e4e2dd',
  surfaceVariant: '#e4e2dd',
  surfaceDim: '#dbdad5',
  primary: '#006a39',
  primaryContainer: '#008649',
  primaryFixed: '#82faab',
  primaryFixedDim: '#64dd91',
  primarySoft: '#e2f6e8',
  secondary: '#29695b',
  secondaryContainer: '#acedda',
  secondaryFixed: '#afefdd',
  gold: '#cca72f',
  goldSoft: '#ffe088',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onBackground: '#1b1c19',
  onSurface: '#1b1c19',
  onSurfaceVariant: '#3e4a3f',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#f6fff4',
  onSecondaryContainer: '#2e6d5f',
  outline: '#6d7a6f',
  outlineVariant: '#bdcabc',
  inverseSurface: '#30312e',
  transparent: 'transparent',
} as const;

export type ColorToken = keyof typeof colors;
